
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='newclear',
    version='0.1.0',
    description='New style CLI builder',
    python_requires='==3.*,>=3.8.0',
    author='Adrien Pensart',
    author_email='crunchengine@gmail.com',
    entry_points={"console_scripts": ["newclear = newclear.main:main"]},
    packages=['newclear'],
    package_dir={"": "."},
    package_data={},
    install_requires=['defopt==6.*,>=6.0.1', 'makefun==1.*,>=1.9.3', 'returns==0.*,>=0.14.0'],
    extras_require={"dev": ["dephell==0.*,>=0.8.3", "flake8==3.*,>=3.8.3", "pylint==2.*,>=2.6.0"]},
)
